#!/bin/bash

 . /etc/environment

echo "Insertar el nombre de usuario:"
read user


if [ "$user" = "" ];then
        echo "ERROR: Necesita insrtar un nombre de usuario"
        exit 1
fi



/usr/sbin/ftpasswd --passwd --file=/conf/ftpd.passwd --name=$user --uid=$uid --gid=$gid --home=/ftp --shell=/bin/false



exit 0