#!/bin/bash


#Creando Archivos si no existen
if [ ! -f /conf/proftpd.conf ];then
	cp -fv /samples/proftpd.conf /conf/

fi

if [ ! -f /conf/ftpd.passwd ];then
	touch /conf/ftpd.passwd

fi

if [ ! -f /conf/ftpd.group ];then
	touch /conf/ftpd.group

fi


#Reparando Permisos:
/bin/chmod -R 700 /conf/*

exec /usr/sbin/proftpd -n -c /conf/proftpd.conf
